version: '3'
include:
  - temporal-docker-compose.yml
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - mw-pg-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    volumes:
      - mw-redis-data:/data

  multiwoven-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - temporal
    env_file: .env
    volumes:
      - .:/rails
    stdin_open: true
    tty: true

  multiwoven-worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
      - redis
      - temporal
    env_file: .env
    volumes:
      - .:/rails
    command: sh -c "./app/temporal/cli/register_namespace && ./app/temporal/cli/worker"

volumes:
  mw-pg-data:
  mw-redis-data: