apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: multiwoven-postgresql-pvc
  name: multiwoven-postgresql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
