apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiwoven-worker
  labels:
    app: multiwoven-worker
    io.kompose.service: multiwoven-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multiwoven-worker
      io.kompose.service: multiwoven-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: multiwoven-worker
        io.kompose.service: multiwoven-worker
    spec:
      containers:
        - name: multiwoven-worker
          image: multiwoven/multiwoven-server:latest
          args:
            - sh
            - -c
            - |
              ./app/temporal/cli/register_namespace && ./app/temporal/cli/worker
          envFrom:
            - configMapRef:
                name: multiwoven-config
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      restartPolicy: Always
