apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiwoven-postgresql
  labels:
    io.kompose.service: multiwoven-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: multiwoven-postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/multiwoven-server-default: "true"
        io.kompose.service: multiwoven-postgresql
    spec:
      containers:
        - name: multiwoven-postgresql
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: multiwoven-config
                  key: DB_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: multiwoven-config
                  key: DB_USERNAME
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: multiwoven-postgresql-pvc
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: multiwoven-postgresql-pvc
          persistentVolumeClaim:
            claimName: multiwoven-postgresql-pvc
