apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: multiwoven-postgresql
  name: multiwoven-postgresql
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: multiwoven-postgresql

