apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  labels:
    io.kompose.service: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: temporal
  template:
    metadata:
      labels:
        io.kompose.network/multiwoven-server-default: "true"
        io.kompose.service: temporal
    spec:
      containers:
        - name: temporal
          image: temporalio/auto-setup:1.22.4
          ports:
            - containerPort: 7233
          env:
            - name: DB
              value: postgresql
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: multiwoven-config
                  key: DB_PORT
            - name: POSTGRES_PWD
              valueFrom:
                configMapKeyRef:
                  name: multiwoven-config
                  key: DB_PASSWORD
            - name: POSTGRES_SEEDS
              valueFrom:
                configMapKeyRef:
                  name: multiwoven-config
                  key: DB_HOST
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: multiwoven-config
                  key: DB_USERNAME
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
      restartPolicy: Always
