---
openapi: 3.0.1
info:
  title: Management API
  version: v1
paths:
  "/api/v1/login":
    post:
      summary: Logs in a user
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: User logged in
        '401':
          description: Invalid credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/v1/workspaces":
    get:
      summary: Lists all workspaces
      tags:
      - Workspaces
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Workspaces retrieved
servers:
- url: http://localhost:3000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- bearerAuth: []
