---
openapi: 3.0.1
info:
  title: Management API
  version: v1
paths:
  "/api/v1/workspaces/{workspace_id}/workspace_users":
    post:
      summary: Adds a user to a workspace
      tags:
      - WorkspaceUsers
      security:
      - bearerAuth: []
      parameters:
      - name: workspace_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '201':
          description: User added to workspace
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                workspace_user:
                  type: object
                  properties:
                    email:
                      type: string
                    role:
                      type: string
                  required:
                  - email
                  - role
              required:
              - workspace_user
  "/api/v1/workspaces/{workspace_id}/workspace_users/{id}":
    put:
      summary: Updates a user's role in a workspace
      tags:
      - WorkspaceUsers
      security:
      - bearerAuth: []
      parameters:
      - name: workspace_id
        in: path
        required: true
        schema:
          type: integer
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: User role updated in workspace
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                role:
                  type: string
              required:
              - role
    delete:
      summary: Removes a user from a workspace
      tags:
      - WorkspaceUsers
      security:
      - bearerAuth: []
      parameters:
      - name: workspace_id
        in: path
        required: true
        schema:
          type: integer
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: User removed from workspace
  "/api/v1/workspaces":
    get:
      summary: Lists all workspaces
      tags:
      - Workspaces
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Workspaces retrieved
    post:
      summary: Creates a workspace
      tags:
      - Workspaces
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: Workspace created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                workspace:
                  type: object
                  properties:
                    name:
                      type: string
                  required:
                  - name
              required:
              - name
  "/api/v1/workspaces/{id}":
    put:
      summary: Updates a workspace
      tags:
      - Workspaces
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Workspace updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                workspace:
                  type: object
                  properties:
                    name:
                      type: string
    delete:
      summary: Deletes a workspace
      tags:
      - Workspaces
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: Workspace deleted
servers:
- url: http://localhost:3000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- bearerAuth: []
