base_uri: "https://pixel-path.multiwoven.com/trackr"
events:
  connectors:
    created: "Created Connector"
    updated: "Updated Connector"
    deleted: "Deleted Connector"
    viewed: "Viewed Connector"
    viewed_all: "Viewed Connectors"
    discovered_catalog: "Discovered Catalog"
    queried_source: "Queried Source"
  models:
    created: "Created Model"
    updated: "Updated Model"
    deleted: "Deleted Model"
    viewed: "Viewed Model"
    viewed_all: "Viewed Models"
  syncs:
    created: "Created Sync"
    updated: "Updated Sync"
    deleted: "Deleted Sync"
    viewed: "Viewed Sync"
    viewed_all: "Viewed Syncs"
